---
# install_other_required_packages.yaml

- name: enable powertools for non Centos
  command: /usr/bin/dnf config-manager --set-enabled powertools
  args:
    warn: false
  when: ansible_facts['distribution'] != "CentOS" 

- name: install other required packages
  yum: name={{ item }} state=latest
  with_items:
  - "@development"
  - mailx
  - xauth
  - xorg-x11-apps
  - xorg-x11-fonts-Type1
  - python3
  - python3-devel
  - python3-pip
  - python3-setuptools
  - Xvfb

- name: upgrade pip3 setuptools
  pip:
    name: setuptools
    executable: pip3
    state: latest

- name: install required python3 modules
  pip:
    name: ["pytest==7.0.1", "pytest-rerunfailures==10.2"]
    executable: pip3
  
