htcondor_fqdn: <REPLACE_ME> # full domain name of your target htcondor host 
htcondor_ipv4: <REPLACE_ME> # ipv4 address of your target htcondor host 
# csv2_fqdn: <REPLACE ME> # full domain name of your target csv2 host 

admin_email: myemail@mydomain # Email address you'd like to recieve admin mail to and generate token with, usually the root on the condor host

# Set installation status for Condor-ce and the atlas config
condor_ce: True

# Only used when condor_ce is true
# Current possible values are atlas and dune
instance: "dune"

# the htcondor install script requires a password
condor_pass: "setapasswordforcondorinstall"

# settings for GSI authentication
htcondor_gsi_dn: "putyourDNhere"
htcondor_cert: "path_to_cert"
htcondor_key:  "path_to_key"

# htcondor_worker_gsi_dn: /C=CA/O=Grid/CN=condorworker/condor.heprc.uvic.ca
# htcondor_worker_cert: /root/grid-security/latest/condorworker/hostcert.pem
# htcondor_worker_key: /root/grid-security/latest/condorworker/hostkey.pem

i_service_connection: 
- ipv4: '{{ htcondor_ipv4 }}' # IPV4 address of your target htcondor host
  ipv4fqdn: '{{ htcondor_fqdn }}'

    #i_virtualhosts:
    #- virtualhost: '{{ i_service_connection.0.ipv4fqdn }}'
    #

job_routes_atlas:
  atlas_sam:
    requirements: "(x509UserProxyVoName =?= \"atlas\" && x509UserProxyFirstFQAN =?= \"/atlas/Role=lcgadmin/Capability=NULL\") ||\  (AuthTokenIssuer =?= \"https://atlas-auth.web.cern.ch/\" &&\  AuthTokenSubject =?= \"c3a22a4c-8257-1abf-562c-4c15e8fac421\")"
    requirements_two: "(TARGET.t1_allow_sam =?= true) && (!StringListMember(\"gpfs_atlas\",t1_GPFS_CHECK ?: \"\",\":\"))"
    maxjobs: 35
    maxidlejobs: 12

  atlas:
    requirements: "(((x509UserProxyVoName =?= \"atlas\") ||\ (AuthTokenIssuer =?= \"https://atlas-auth.web.cern.ch/\" && StringListMember(AuthTokenSubject ?: \"\", \"7dee38a3-6ab8-4fe2-9e4c-123abc82f732:642c5236-548b-2ad1-3b42-6fab13b21f03\", \":\"))) && (iRqueue == \"atlas\"))"
    requirements_two: "(!StringListMember(\"gpfs_atlas\",t1_GPFS_CHECK ?: \"\",\":\")) && (t1_allow_sam =!= true)"
    maxjobs: 3500
    maxidlejobs: 1280

  atlas_ecdf:
    requirements: "queue == \"UKI-SCOTGRID-ECDF_CLOUD\""
    requirements_two: "(group_name == \"new-atlas\") && (target_alias == \"uki-scotgrid-ecdf_cloud\") && (TARGET.Cpus >= RequestCpus) && (TARGET.Memory >= RequestMemory) && (TARGET.HasFileTransfer)"
    maxjobs: 3500
    maxidlejobs: 1280

  atlas_uvic:
    requirements: "queue == \"CA-IAAS-T3\""
    requirements_two: "(group_name == \"atlas-uvic\") && (target_alias == \"ca-iaas-t3\") && (TARGET.Cpus >= RequestCpus) && (TARGET.Memory >= RequestMemory) && (TARGET.HasFileTransfer)"
    maxjobs: 3500
    maxidlejobs: 1280

job_routes_dune:
  dune:
    requirements_two: "(group_name == \"dune-mentat\") && (TARGET.Cpus >= RequestCpus) && (TARGET.Memory >= RequestMemory) && (TARGET.HasFileTransfer)"
    maxjobs: 3500
    maxidlejobs: 1280

job_routes: "{{ lookup('vars','job_routes_' + instance) }}"

htcondor_collector_name: Production Pool # short desciption of your htcondor pool

