htcondor_fqdn: <REPLACE ME> # full domain name of your target htcondor host ex
# csv2_fqdn: <REPLACE ME> # full domain name of your target csv2 host ex

htcondor_token_auth: True


admin_email: <REPLACE ME> # Email address you'd like to recieve admin mail to and generate token with, usually the root on the csv2 host

i_service_connection: 
- ipv4: <REPLACE ME> # IPV4 address of your target csv2 host
  ipv4fqdn: '{{ htcondor_fqdn }}'

i_virtualhosts:
- virtualhost: '{{ i_service_connection.0.ipv4fqdn }}'
