htcondor_fqdn: <REPLACE ME> # full domain name of your target htcondor host ex
# csv2_fqdn: <REPLACE ME> # full domain name of your target csv2 host ex

admin_email: <REPLACE ME> # Email address you'd like to recieve admin mail to and generate token with, usually the root on the csv2 host

# Set installation status for Condor-ce and the atlas config
condor_ce: True
atlas_enabled: True

# settings for GSI authentication
htcondor_gsi_dn: /C=CA/O=Grid/CN=csv2.heprc.uvic.ca
htcondor_cert: /root/grid-security/latest/csv2/hostcert.pem
htcondor_key: /root/grid-security/latest/csv2/hostkey.pem

# htcondor_worker_gsi_dn: /C=CA/O=Grid/CN=condorworker/condor.heprc.uvic.ca
# htcondor_worker_cert: /root/grid-security/latest/condorworker/hostcert.pem
# htcondor_worker_key: /root/grid-security/latest/condorworker/hostkey.pem

i_service_connection: 
- ipv4: <REPLACE ME> # IPV4 address of your target htcondor host
  ipv4fqdn: '{{ htcondor_fqdn }}'

i_virtualhosts:
- virtualhost: '{{ i_service_connection.0.ipv4fqdn }}'

htcondor_collector_name: Production Pool # short desciption of your htcondor pool
