---
# install_other_required_packages.yaml

- name: enable PowerTools for Centos 8
  command: /usr/bin/dnf config-manager --set-enabled powertools
  args:
    warn: false
  when: ansible_facts['distribution_major_version'] == "8"

- name: install other required packages
  yum:
    name: ['@development', 'mailx', 'xauth', 'xorg-x11-apps', 'xorg-x11-fonts-Type1']
    state: latest

- name: add grid canada to ca bundle
  script: bash-add_grid_canada_to_ca_bundle creates=/root/ansible_script_logs/bash-add_grid_canada_to_ca_bundle.log

- name: create symbolic link for CABundle.crt
  file:
    src: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
    dest: "/etc/ssl/certs/CABundle.crt"
    state: link

