---
# configure_sshd.yaml - set_fact no_firewall to disable the firewall.

- name: change firewall to open non-standard ssh port on public zone
  firewalld: port={{ ansible_ssh_port }}/tcp state=enabled permanent=true immediate=true zone=public
  when: no_firewall is not defined
  ignore_errors: yes

- name: configure sshd
  template: src=etc_ssh_sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
    - restart sshd

- name: change firewall to close standard ssh port on public zone
  firewalld: service=ssh state=disabled permanent=true immediate=true zone=public
  when: no_firewall is not defined
  ignore_errors: yes

- name: change firewall to close standard ssh port on internal zone
  firewalld: service=ssh state=disabled permanent=true immediate=true zone=internal
  when: no_firewall is not defined
  ignore_errors: yes

- name: open external network ports via tcp 
  firewalld: zone=public port=0-65535/tcp  state=enabled immediate=yes permanent=yes
  when: no_firewall is defined
  ignore_errors: yes

- name: open external network ports via udp 
  firewalld: zone=public port=0-65535/udp  state=enabled immediate=yes permanent=yes
  when: no_firewall is defined
  ignore_errors: yes

- name: meta
  meta: flush_handlers
