---
# file: define_etc_hosts.yaml - inventory variables build a standard /etc/hosts

- name: build a standard etc hosts file
  template: src=etc_hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
  when: (container is undefined) or (container == False)

