---
- name: Ensure hosts backup directory exists
  ansible.builtin.file:
    path: /mnt/hosts/{{ i_service_connection.0.ipv4fqdn }}
    state: directory
      #    owner: root
      #    group: root
    mode: "755"
...
