---
# file: install_configure_mariadb.yaml
#
# Depends on the following variables:
#
#   {{ i_internal_connection.0.ipv4 }}
#   {{ i_internal_connection.0.ipv4fqdn }}
#   {{ database_user_passwords['root'] }}
#   {{ database_user_passwords['change_from_old_root'] }}
#
#  and the following optional variables:
#   {{ public_mariadb }}        - Anything other than "true" is treated as "false". 
#   {{ etc_my_cnf_d }}          - A list of configuration files, see play "configure mariadb server" below.

- name: if required (public_mariadb = true specified), open the firewall for public access
  firewalld: service=mysql state=enabled permanent=true immediate=true zone=public
  when:
  - public_mariadb is defined
  - public_mariadb == true
  - (container is undefined) or (container == False)
  ignore_errors: yes

- name: setup the MariaDB repository
  copy:
    src: etc_yum.repos.d_MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo
    owner: root
    group: root
    mode: 0644

- name: update MariaDB repo for Alma 9
  replace:
    path: /etc/yum.repos.d/MariaDB.repo
    regexp: '^baseurl = .*'
    replace: 'baseurl = http://mirror.mariadb.org/yum/11.2.1/rhel9-amd64/'
  when: ansible_facts['distribution_major_version'] == '9'

- name: install mariadb (MySQL) packages
  yum:
    name: ['expect', 'MariaDB-server', 'MariaDB-client', 'MariaDB-devel', 'MariaDB-common',
          'MariaDB-shared', 'zlib-devel', 'openssl-devel', 'python3-PyMySQL']
    state: latest
  notify:
  - restart mariadb

- name: install mariadb (MySQL) packages on centos 7
  yum:
    name: ['MariaDB-compat', 'MySQL-python', 'python2-PyMySQL']
    state: latest
  notify:
  - restart mariadb
  when: ansible_facts['distribution_major_version'] == '7'

- name: ensure mariadb is running and enabled with service
  service: name=mariadb state=restarted enabled=yes
  when: (container is undefined) or (container == False)

- name: ensure mariadb is running and enabled with systemd
  systemd: name=mariadb state=started enabled=yes
  when: 
  - container is defined
  - container == True

- name: meta
  meta: flush_handlers

- name: ensure mysql pid is down
  shell: pkill -9 mysql
  ignore_errors: yes
  when:
  - container is defined
  - container == True

- name: restart mariadb
  systemd:
      name: mariadb
      state: restarted
  when:
  - container is defined
  - container == True

- name: secure mariadb database
  script: expect-mariadb_secure_database "{{ database_user_passwords['root'] }}" "{{ database_user_passwords['change_from_old_root'] }}" "{{ ansible_facts['distribution_major_version'] }}" creates=/root/ansible_script_logs/expect-mariadb_secure_database.log

