---
# file: install_CentOS_HAProxy.yaml

- name: install HAProxy on centos 7
  yum:
    name: rh-haproxy18
    state: latest
  when: ansible_facts['distribution_major_version'] == '7'

- name: install HAProxy on almalinux 9
  yum:
    name: haproxy
    state: latest
  when: ansible_facts['distribution_major_version'] == '9'


