---
# file: install_configure_mariadb.yaml
#
# Depends on the following variables:
#
#   {{ i_internal_connection.0.ipv4 }}
#   {{ i_internal_connection.0.ipv4fqdn }}
#   {{ database_user_passwords['root'] }}
#   {{ database_user_passwords['change_from_old_root'] }}
#
#  and the following optional variables:
#   {{ public_mariadb }}        - Anything other than "true" is treated as "false". 
#   {{ etc_my_cnf_d }}          - A list of configuration files, see play "configure mariadb server" below.

- name: if required (public_mariadb = true specified), open the firewall for public access
  firewalld: service=mysql state=enabled permanent=true immediate=true zone=public
  when:
  - public_mariadb is defined
  - public_mariadb == true
  - (container is undefined) or (container == False)
  ignore_errors: yes

# if this installs mariadb 11 ssl will break
- name: ensure mariadb installed
  ansible.builtin.yum:
    name: mariadb
    state: present

- name: gather package facts
  ansible.builtin.package_facts:
    manager: rpm

- name: fail if mariadb other than 10 present
  ansible.builtin.fail:
    msg: MariaDB not 10 was installed. 
  when: "not ansible_facts.packages['mariadb'][0].version | regex_search('^10.*')"

- name: install mariadb (MySQL) packages
  yum:
    name: ['expect', 'mariadb-server',  'mariadb-devel', 'mariadb-common',
           'zlib-devel', 'openssl-devel', 'python3-PyMySQL']
    state: latest
  notify:
  - restart mariadb
### removed 'MariaDB-shared','mariadb-client',

- name: ensure mysql standalone error directories exist
  ansible.builtin.file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: root

- name: ensure mariadb is running and enabled with service
  service: name=mariadb state=restarted enabled=yes
  when: (container is undefined) or (container == False)

- name: ensure mariadb is running and enabled with systemd
  systemd: name=mariadb state=started enabled=yes
  when: 
  - container is defined
  - container == True

- name: meta
  meta: flush_handlers

- name: ensure mysql pid is down
  shell: pkill -9 mysql
  ignore_errors: yes
  when:
  - container is defined
  - container == True

- name: restart mariadb
  systemd:
      name: mariadb
      state: restarted
  when:
  - container is defined
  - container == True

- name: secure mariadb database
  script: expect-mariadb_secure_database "{{ database_user_passwords['root'] }}" "{{ database_user_passwords['change_from_old_root'] }}" "{{ ansible_facts['distribution_major_version'] }}" creates=/root/ansible_script_logs/expect-mariadb_secure_database.log

