---
# file: configure_ntpd.yaml - add local times server time.uvic.ca.

- name: install packages required by ntpd
  yum:
    name: ['ntp']
    state: latest
  ignore_errors: yes
  notify:
    - restart ntpd

- name: meta
  meta: flush_handlers

