---
# file: install_python3_mod_wsgi.yaml
# cp /opt/rh/httpd24/root/usr/lib64/httpd/modules/mod_rh-python36-wsgi.so /lib64/httpd/modules
# cp /opt/rh/httpd24/root/etc/httpd/conf.modules.d/10-rh-python36-wsgi.conf /etc/httpd/conf.modules.d 


- name: install the python3 mod_wsgi module (rpm places it in /opt)
  yum:
    name:
      - python3-mod_wsgi
    state: latest


