---
# file: perform_updates.yaml - but not automatically.
- name: Ensure epel-release is present
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: update all installed packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
  ignore_errors: true

- name: install other packages
  ansible.builtin.dnf:
    name: ['nano', 'mc']
    state: present


