---
# file: perform_updates.yaml - but not automatically.

- name: Install elrepo gpg key
  rpm_key:
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    state: present

- name: Install elrepo repo
  package:
    name: https://www.elrepo.org/elrepo-release-{{ansible_facts['distribution_major_version']}}.el{{ansible_facts['distribution_major_version']}}.elrepo.noarch.rpm

- name: disable yum auto_updates
  script: bash-disable_yum_auto_updates creates=/root/ansible_script_logs/bash-disable_yum_auto_updates.log

- name: install other packages
  yum:
    name: ['nano', 'mc']
    state: present

- name: update all installed packages
  yum:
    name: '*'
    state: latest
  ignore_errors: true
