# update_customize_sh.yaml

- name: create pi
  shell: /usr/sbin/ip -o route get 8.8.8.8 | sed "s/^.* dev \([[:alnum:]]*\) .*/\1/g"
  register: PI

- name: get the ip address
  shell: ip route | grep "{{PI.stdout}}.*link src" | awk '{print $1}'
  register: IP

- name: get the number of cores
  shell: grep -c 'processor' /proc/cpuinfo
  register: VCORE

- name: create a list of cores
  shell: seq -s, 1 {{VCORE.stdout}}
  register: SEQUENCE

- name: get the total memory
  shell: grep MemTotal /proc/meminfo | awk '{print $2}'
  register: MEM

- name: save 10% of memory for os and convert to MB
  set_fact:
    CACHE_MEM: "{{ ((MEM.stdout | int) / (VCORE.stdout | int) * 9 / 10000) | int }}"

- name: get the disk space 
  shell: df -H --output=avail /var/cache | sed 1d | tr -d "G"
  register: DS

- name: save 20% for disk space and convert to MB
  set_fact:
    CACHE_DIR: "{{ ((DS.stdout | int) / (VCORE.stdout | int) / 5 * 4000) | int }}"

- name: copy customize.sh to the machine
  template:
    src: customize.sh
    dest: /etc/squid/customize.sh
    owner: squid
    group: squid
    mode: u+x

- name: enable frontier-squid
  shell: systemctl enable frontier-squid

- name: restart frontier-squid 
  shell: systemctl restart frontier-squid 

- name: run shoal agent installer with default options
  shell: shoal-agent-installation.sh -b

- name: update the server name if specified
  replace:
    path: /etc/shoal/shoal_agent.conf
    regexp: "^amqp_server_url=.*"
    replace: "amqp_server_url={{ amqp_server_url }}"
  when: amqp_server_url is defined

- name: add use credentials configuration if using credentials
  lineinfile:
    path: /etc/shoal/shoal_agent.conf
    regexp: "^use_credentials=.*"
    line: "use_credentials=True"
    insertafter: "^amqp_exchange=.*"
  when: (amqp_use_credentials is defined) and (amqp_use_credentials == True)

- name: add the username configuration if using credentials
  lineinfile:
    path: /etc/shoal/shoal_agent.conf
    regexp: "^amqp_username=.*"
    line: "amqp_username={{ amqp_users }}"
    insertafter: "^use_credentials=.*"
  when: (amqp_use_credentials is defined) and (amqp_use_credentials == True)

- name: add the password configuration if using credentials
  lineinfile:
    path: /etc/shoal/shoal_agent.conf
    regexp: "^amqp_password=.*"
    line: "amqp_password={{ amqp_user_passwords[item] }}"
    insertafter: "^amqp_username=.*"
  with_items: 
  - "{{ amqp_users }}"
  when: (amqp_use_credentials is defined) and (amqp_use_credentials == True)

- name: restart the shoal-agent
  service:
    name: shoal-agent
    state: restarted