###############################################################################
#
# HTCondor-CE manual GSI/VOMS authentication mappings
#
# This file will NOT be overwritten upon RPM upgrade.
#
###############################################################################

# Using SSL authentication for IGTF certificates requires the issuer CAs to
# be installed in /etc/grid-security/certificates. If you would also like to
# authenticate VOMS attributes, *.lsc files should be installed in
# /etc/grid-security/vomsdir/

# To configure authorization for users submitting jobs to your HTCondor-CE,
# uncomment and replace <DISTINGUISHED NAME> and <USERNAME> (escaping any '/'
# with '\/') with the Distinguished Name (DN) of the incoming user certificate
# and the unix account under which the job should run, respectively:
#
# SSL /<DISTINGUISHED NAME>/ <USERNAME>

# VOMS attributes can also be used for mapping:
#
# SSL /<DISTINGUISHED NAME>,<VOMS FQAN 1>,<VOMS FQAN 2>,...,<VOMSFQAN N>/ <USERNAME>

# The second field should be a Perl Compatible Regular Expression (PCRE), thus
# allowing you to accept any DN with a given VOMS FQAN. For example, to map any
# GLOW certificate with the 'htpc' role to the 'glow' user, add a line that
# looks like the following:
#
# SSL /.*,\/GLOW\/Role=htpc.*/ glow


SSL /\/DC=ch\/DC=cern\/OU=Organic Units\/OU=Users\/CN=litmaath\/CN=410032\/CN=Maarten Litmaath,.*/ ops
SSL /\/DC=EU\/DC=EGI\/C=GR\/O=Robots\/O=Greek Research and Technology Network\/CN=Robot:argo-egi@grnet.gr,.*/ ops
SSL /\/DC=EU\/DC=EGI\/C=HR\/O=Robots\/O=SRCE\/CN=Robot:argo-egi@cro-ngi.hr,.*/ ops
SSL /\/DC=EU\/DC=EGI\/C=GR\/O=Robots\/O=Greek Research and Technology Network\/CN=Robot:argo-secmon@grnet.gr,.*/ ops

SSL /\/DC=ch\/DC=cern\/OU=Organic Units\/OU=Users\/CN=vokac\/CN=610071\/CN=Petr Vokac/ ops

