- name: set_fact
  set_fact:
    certificate_users: []
  when: certificate_users is undefined

- name: set_fact
  set_fact:
    certificate_users: "{{ certificate_users + [item] }}"
  with_items: "{{ additional_certificate_users }}"
  when: additional_certificate_users is defined

- name: create user certificate directories
  file:
    dest: "{{ item.globus }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0755
  with_items:
  - "{{ certificate_users }}"

- name: create empty usercert pem files for certificate users
  file:
    dest: "{{ item.globus }}/{{ item.pfx }}cert.pem"
    state: touch
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0444
  with_items:
  - "{{ certificate_users }}"

- name: create empty userkey pem files for certificate users
  file:
    dest: "{{ item.globus }}/{{ item.pfx }}key.pem"
    state: touch
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0400
  with_items:
  - "{{ certificate_users }}"

- name: install bash script to update cert and key for certificate users
  template:
    src: etc_letsencrypt_renewal-hooks_post_copy_certificates_to_users.j2
    dest: /etc/letsencrypt/renewal-hooks/post/copy_certificates_to_users.sh
    owner: root
    group: root
    mode: 0700
  when:
  - certificate_users is defined

#- name: copy certificates to users crontab entry
#  copy:
#    src: etc_cron.d_copy-certificates-to-users
#    dest: /etc/cron.d/copy-certificates-to-users
#    owner: root
#    group: root
#    mode: 0644
#  when:
#  - certificate_users is defined

- name: copy certificates to users
  command:
    cmd: /etc/letsencrypt/renewal-hooks/post/copy_certificates_to_users.sh
  when:
  - certificate_users is defined