# install_htcondor_23.yaml

- name: download htcondor script
  get_url:
    url: https://get.htcondor.org
    dest: /tmp/install_htcondor.sh
    validate_certs: yes

- name: run the script
  shell: /bin/bash /tmp/install_htcondor.sh --no-dry-run
  ignore_errors: yes
  when: ansible_facts['distribution_major_version'] == '9'

- name: run the script for centos 7
  shell: /bin/bash /tmp/install_htcondor.sh --no-dry-run --channel stable
  ignore_errors: yes
  when: ansible_facts['distribution_major_version'] == '7'

- name: allow SHA1 Hashing
  shell: update-crypto-policies --set DEFAULT:SHA1
  when: ansible_facts['distribution_major_version'] == '9'

- name: install HTCondor repository GPG keys
  rpm_key:
    key: http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
    state: present

- name: install HTCondor
  yum:
    name: ['condor-all']
    state: latest