#
# Requirements:
# SSL, SSL cert, forward/reverse DNS, port 9619, htcondor
#
# yum package: htcondor-ce-condor
#
#Check if certificate installed?
#

- name: install HTCondor Compute Entrypoint (htcondor-ce) package
  yum:
    name: ['htcondor-ce-condor']
    state: latest

- name: open HTCondor ce service port
  firewalld: zone=public port="9619/tcp"  state=enabled immediate=yes permanent=yes
  ignore_errors: yes

- name: Ensure group exists for user to run jobs (atlas, dune, etc.)
  group:
    name: "{{ instance }}"
    state: present

- name: Ensure ops group exists 
  group:
    name: "ops"
    state: present

- name: Ensure user exists for running jobs (atlas, dune, etc.)
  user:
    name: "{{ instance }}"
    group: "{{ instance }}"
    state: present

- name: Ensure ops user exists
  user:
    name: "ops"
    group: "ops"
    state: present

- name: Copy condor-ce mapfiles
  ansible.builtin.copy:
    src: "etc_condor-ce_mapfiles.d_{{item}}"
    dest: "/etc/condor-ce/mapfiles.d/{{item}}"
    owner: root
    group: root
    mode: '0644'
  with_items:
   - "10-scitokens-{{ instance }}.conf"
   - "10-ssl.conf"

- name: Copy dune condor-ce mapfile
  ansible.builtin.copy:
    src: "etc_condor-ce_mapfiles.d_10-scitokens-dune.conf"
    dest: "/etc/condor-ce/mapfiles.d/10-scitokens.conf"
    owner: root
    group: root
    mode: '0644'
  when: instance == "dune"

- name: copy condor-ce routing config
  template:
    src: "etc_condor-ce_config.d_{{item}}"
    dest: "/etc/condor-ce/config.d/{{item}}"
  with_items:
   - 01-ce-router.conf
   - 02-ce-condor.conf

- name: copy atlas condor-ce auth config
  copy:
    src: "etc_condor-ce_config.d_{{item}}"
    dest: "/etc/condor-ce/config.d/{{item}}"
    owner: root
    group: root
    mode: '0644'
  with_items:
   - 01-ce-auth.conf
   - 99-voms.conf
   - 99-ssl.conf
   - 99-fix-client-auth.conf

- name: copy dune condor-ce local config
  template:
    src: "etc_condor-ce_config.d_{{item}}.j2"
    dest: "/etc/condor-ce/config.d/{{item}}"
    owner: root
    group: root
    mode: '0644'
  with_items:
   - 99-local.conf
  when: instance == "dune"

- name: Install WLCG repo 
  yum_repository:
    name: WLCG
    description: WLCG Linux software repo
    baseurl: https://linuxsoft.cern.ch/wlcg/el9/x86_64/

- name: Install atlas and ops voms rpms
  dnf:
    name: 
      - wlcg-iam-lsc-atlas
      - wlcg-iam-lsc-ops
    state: present
  when: instance == "atlas"

- name: Create voms directory
  file:
    path: "/etc/grid-security/vomsdir/dune/"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: instance == "dune"

- name: Copy lsc files for Dune (couldn't find rpm)
  copy:
    src: "etc_grid-security_vomsdir_dune_{{item}}"
    dest: "/etc/grid-security/vomsdir/dune/{{item}}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - voms1.fnal.gov.lsc
    - voms2.fnal.gov.lsc
  when: instance == "dune"
