- name: get the installer for the condor poller
  get_url:
    url: "https://{{ csv2_fqdn }}/repo/install_condor_poller.sh"
    dest: /tmp/install_condor_poller.sh
    mode: a+x
    owner: root
    group: root

- name: install wget
  yum:
    name: wget

- name: run the install script
  shell: yes | /tmp/install_condor_poller.sh

- name: make the directory
  file:
    path: /etc/cloudscheduler
    state: directory
    owner: root
    group: root
    mode: 0700

- name: disable the poller
  shell: /opt/cloudscheduler/utilities/service_disable_condor_poller

- name: enable the poller
  shell: /opt/cloudscheduler/utilities/service_enable_condor_poller

- name: copy htcondor python packages for token auth to cloudscheduler folder
  shell: cp -r /usr/lib64/python3.6/site-packages/htcondor /opt/cloudscheduler/python3/lib/python3.6/site-packages/
  when: ansible_facts['distribution_major_version'] == '7' and (htcondor_token_auth is defined) and (htcondor_token_auth == True)

- name: copy htcondor python packages for token auth to cloudscheduler folder
  shell: cp -r /usr/lib64/python3.6/site-packages/classad /opt/cloudscheduler/python3/lib/python3.6/site-packages/
  when: ansible_facts['distribution_major_version'] == '7' and (htcondor_token_auth is defined) and (htcondor_token_auth == True)

- name: restart the condor poller
  service:
    name: csv2-condor-poller
    state: restarted