# htcondor server setup yaml

- include_vars: htcondor-public-default-vars.yaml
- include_vars: htcondor-public-secrets.yaml
- include_vars: htcondor-public-vars.yaml

- import_tasks: prepare.yaml
- import_tasks: install_htcondor.yaml


