# Timezone
timezone: America/Vancouver

# Admin email for root mail forwarding
admin_email: heprc-operations@lists.uvic.ca

# Branch for ci server to follow
csv2_branch: stable-2.10

csv2_ci_fqdn: <REPLACE ME>

i_service_connection:
-
    ipv4: <REPLACE ME> # IPV4 address of your target csv2 host
    ipv4fqdn: '{{ csv2_ci_fqdn }}'
