# Overriding the following defaults varables (see csv2-public-default-vars.yaml):

csv2_fqdn: elephant136.heprc.uvic.ca #full domain name of your target csv2 host ex

cs_git_branch: IceyMu-patch-1
db_upgrade_file: none
schema_model: stable-2.10.4.rc1

#admin_email: "{{undef(hint='Admin email not provided')}}" # Email address you'd like to recieve admin mail to, usually the root on the csv2 host
admin_email: fizz@uvic.ca

install_phpMyAdmin: False
web_debug: True

favicon_colour: red

container: True
local_web: False

openstack_vm: True
ci_target: True

i_service_connection:
-
    #ipv4: "{{undef(hint='IPV4 address not provided')}}" # IPV4 address of your target csv2 host
    ipv4: elephant136.heprc.uvic.ca
    ipv4fqdn: '{{ csv2_fqdn }}'

i_virtualhosts:
-
    virtualhost: '{{ i_service_connection.0.ipv4fqdn }}'

