# Overriding the following defaults varables (see csv2-public-default-vars.yaml):

csv2_fqdn: elephant179.heprc.uvic.ca

cs_git_branch: stable-2.10.4
db_upgrade_file: none
schema_model: stable-2.10.4.rc1

admin_email: root@elephant179.heprc.uvic.ca

install_phpMyAdmin: False
web_debug: True

favicon_colour: red

container: True
local_web: False

openstack_vm: True
ci_target: True

i_service_connection:
-
    ipv4: '206.12.154.179'
    ipv4fqdn: '{{ csv2_fqdn }}'

i_virtualhosts:
-
    virtualhost: '{{ i_service_connection.0.ipv4fqdn }}'

