---

- name: generate condor_poller configuration file
  template:
    src: "tmp_gentgz_cloudscheduler_etc_cloudscheduler_condor_poller.yaml.j2.pfile"
    dest: /opt/cloudscheduler/etc/cloudscheduler/condor_poller.yaml
    owner: condor
    group: condor
    mode: "0400"


- name: Generate repository index.html
  ansible.builtin.template:
    src: "opt_cloudscheduler_repository_index.html.j2.pfile"
    dest: /opt/cloudscheduler/repository/index.html
    owner: root
    group: root
    mode: "0644"

- name: Generate condor poller install script
  ansible.builtin.template:
    src: "opt_cloudscheduler_repository_install_condor_poller.sh.j2"
    dest: /opt/cloudscheduler/repository/install_condor_poller.sh
    owner: root
    group: root
    mode: "0644"

- name: Copy condor poller build sh script
  ansible.builtin.copy:
    src: files/generate_condor_poller_tarball.sh   
    dest: /tmp/generate_condor_poller_tarball.sh 
    owner: root 
    mode: "0755"

- name: Run condor poller build script
  command: /tmp/generate_condor_poller_tarball.sh
...
