---

- name: create condor_poller directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - /opt/cloudscheduler/repository
  - /tmp/gentgz/cloudscheduler/data_collectors/condor
  - /tmp/gentgz/cloudscheduler/etc/cloudscheduler
  - /tmp/gentgz/cloudscheduler/etc/init.d
  - /tmp/gentgz/cloudscheduler/etc/systemd/system
  - /tmp/gentgz/cloudscheduler/lib
  - /tmp/gentgz/cloudscheduler/utilities

- name: stat
  stat:
    path: /tmp/gentgz/cloudscheduler/data_collectors/condor/cloudscheduler
  register: sym

- name: create cloudscheduler library link
  command:
    cmd: "ln -s ../../../cloudscheduler/ cloudscheduler"
    chdir: /tmp/gentgz/cloudscheduler/data_collectors/condor
  when: sym.stat.islnk is not defined

- name: copy condor_poller files
  copy:
    remote_src: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
  - {src: /opt/cloudscheduler/data_collectors/condor/condor_poller.py,           dest: /tmp/gentgz/cloudscheduler/data_collectors/condor/condor_poller.py,           mode: '0644'}
  - {src: /opt/cloudscheduler/etc/init.d/csv2-condor-poller.pfile,                  dest: /tmp/gentgz/cloudscheduler/etc/init.d/csv2-condor-poller.pfile,                  mode: '0644'}
  - {src: /opt/cloudscheduler/etc/systemd/system/csv2-condor-poller.service.pfile,  dest: /tmp/gentgz/cloudscheduler/etc/systemd/system/csv2-condor-poller.service.pfile,  mode: '0644'}
  - {src: /opt/cloudscheduler/lib/attribute_mapper.py,                           dest: /tmp/gentgz/cloudscheduler/lib/attribute_mapper.py,                           mode: '0644'}
  - {src: /opt/cloudscheduler/lib/db_config.py,                                  dest: /tmp/gentgz/cloudscheduler/lib/db_config.py,                                  mode: '0644'}
  - {src: /opt/cloudscheduler/lib/fw_config.py,                                  dest: /tmp/gentgz/cloudscheduler/lib/fw_config.py,                                  mode: '0644'}
  - {src: /opt/cloudscheduler/lib/poller_functions.py,                           dest: /tmp/gentgz/cloudscheduler/lib/poller_functions.py,                           mode: '0644'}
  - {src: /opt/cloudscheduler/lib/ProcessMonitor.py,                             dest: /tmp/gentgz/cloudscheduler/lib/ProcessMonitor.py,                             mode: '0644'}
  - {src: /opt/cloudscheduler/lib/log_tools.py,                                     dest: /tmp/gentgz/cloudscheduler/lib/log_tools.py,                                     mode: '0644'}
  - {src: /opt/cloudscheduler/lib/schema.py,                                     dest: /tmp/gentgz/cloudscheduler/lib/schema.py,                                     mode: '0644'}
  - {src: /opt/cloudscheduler/lib/watchdog_utils.py,                             dest: /tmp/gentgz/cloudscheduler/lib/watchdog_utils.py,                             mode: '0644'}
  - {src: /opt/cloudscheduler/utilities/service_disable_condor_poller,              dest: /tmp/gentgz/cloudscheduler/utilities/service_disable_condor_poller,              mode: '0744'}
  - {src: /opt/cloudscheduler/utilities/service_enable_condor_poller,               dest: /tmp/gentgz/cloudscheduler/utilities/service_enable_condor_poller,               mode: '0744'}

- name: generate condor_poller configuration file
  template:
    src: "tmp_gentgz_cloudscheduler_etc_cloudscheduler_condor_poller.yaml.j2.pfile"
    dest: /tmp/gentgz/cloudscheduler/etc/cloudscheduler/condor_poller.yaml
    owner: condor
    group: condor
    mode: "0400"

- name: Remove certificate references from condor_poller config
  ansible.builtin.lineinfile:
    path: /tmp/gentgz/cloudscheduler/etc/cloudscheduler/condor_poller.yaml
    regexp: "^{{ item }}"
    line: "{{ item }}"
  loop:
    - "    condor_worker_cert:"
    - "    condor_worker_key:"

- name: Generate repository index.html
  ansible.builtin.template:
    src: "opt_cloudscheduler_repository_index.html.j2.pfile"
    dest: /opt/cloudscheduler/repository/index.html
    owner: root
    group: root
    mode: "0644"

- name: Generate condor poller install script
  ansible.builtin.template:
    src: "opt_cloudscheduler_repository_install_condor_poller.sh.j2"
    dest: /opt/cloudscheduler/repository/install_condor_poller.sh
    owner: root
    group: root
    mode: "0644"

- name: build the condor_poller tarball
  command:
    cmd: "tar -czvf /opt/cloudscheduler/repository/condor_poller.tar.gz cloudscheduler"
    chdir: /tmp/gentgz

- name: remove the temporary condor_poller gentgz directory
  file:
    path: /tmp/gentgz
    state: absent

...
