# install_EL7_HTCondor.yaml

- name: check status of htcondor install # need to fix!!!
  shell: yum list installed | grep htcondor-release | wc -l
  register: condor_install
  ignore_errors: yes

- name: install htcondor
  shell: curl -fsSL https://get.htcondor.org | sudo /bin/bash -s -- --no-dry-run
  when: condor_install.stdout == "0"

- name: allow SHA1 Hashing
  shell: update-crypto-policies --set DEFAULT:SHA1

- name: install HTCondor repository GPG keys
  rpm_key:
    key: http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
    state: present

- name: install HTCondor
  yum:
    name: ['condor-all']
    state: latest

