# install_HTCondor.yaml

# New condor setup
- name: configure HTCondor repository
  get_url:
    url: https://get.htcondor.org
    dest: /tmp/htcondor_repo_setup
    mode: +x

- name: setup HTCondor repo
  shell: /tmp/htcondor_repo_setup --no-dry-run

# Old condor setup
# install_EL7_HTCondor.yaml

#- name: configure HTCondor repository
#  get_url:
#    url: http://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo
#    dest: /etc/yum.repos.d/htcondor-stable-rhel7.repo
#    mode: 0644

#- name: install HTCondor repository GPG keys
#  rpm_key:
#    key: http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
#    state: present

#- name: install HTCondor
#  yum:
#    name: ['condor-all']
#    state: latest
