---
# InfluxDb 

- name: Install python2 pip
  yum:
    name: python2-pip
  when: ansible_facts['distribution_major_version'] == "7"

- name: determine package versions
  set_fact:
    certifi_version: "{{ 'certifi' if ansible_facts['distribution_major_version'] == '9' else 'certifi<=2020.4.5.1' }}"
    requests_version: "{{ 'latest' if ansible_facts['distribution_major_version'] == '9' else '2.24.0' }}"

- name: Install certifi python package
  pip:
    name: "{{ certifi_version }}"

- name: Install requests python package version for influx.
  pip:
    name: requests
    version: "{{ requests_version }}"

- name: install msgpack depdenancy for influxdb
  pip:
    name: msgpack
    version: 1.0.0

- name: Install InfluxDB python package.
  pip:
    name: influxdb

- name: Add InfluxDB repository
  yum_repository:
    name: influxdb-repo
    description: InfluxDB YUM repo
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: no

- name: install InfluxDB
  yum:
    name: ['influxdb']
    state: latest

- name: Start service InfluxDB
  service:
    name: influxdb
    state: started

- name: Wait for InfluxDB to be ready
  wait_for:
    port: 8086

- name: Create database
  influxdb_database:
      database_name: "csv2_timeseries"
      udp_port: 4444
  ignore_errors: true
