---
# InfluxDb 

- name: Install python2 pip
  yum:
    name: python2-pip

- name: Install InfluxDB python package.
  pip:
    name: ["requests", "influxdb"]

- name: Add InfluxDB `repository
  yum_repository:
    name: influxdb-repo
    description: InfluxDB YUM repo
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: no

- name: install InfluxDB
  yum:
    name: ['influxdb']
    state: latest

- name: install influxDB configuration file
  copy:
    src: etc_influxdb_influxdb.conf
    dest: /etc/influxdb/influxdb.conf 

- name: Start service InfluxDB
  service:
    name: influxdb
    state: started

- name: Wait for InfluxDB to be ready
  wait_for:
    port: 8086

- name: Create database
  influxdb_database:
      database_name: "csv2_timeseries"
      udp_port: 4444
