---
# install_other_required_packages.yaml

- name: enable PowerTools for Centos 8
  command: /usr/bin/dnf config-manager --set-enabled powertools
  args:
    warn: false
  when: ansible_facts['distribution_major_version'] == "8"

- name: enable CRB for EL9
  command: dnf config-manager --set-enabled crb
  args:
    warn: false
  when: ansible_facts['distribution_major_version'] == "9"

# TODO see if xorg-x11-apps is really needed
- name: install other required packages
  package:
    name: ['@development', 's-nail', 'xauth', 'xorg-x11-fonts-Type1']
    state: latest
