---
# cloudscheduler (v2) server maim.yaml

- name: Set fact public_mariadb
  ansible.builtin.set_fact:
    public_mariadb: false
  when: internal_system_install is not defined

- name: Include vars csv2-public-secret-vars.yaml
  ansible.builtin.include_vars: "csv2-public-secrets.yaml"
  when: internal_system_install is not defined

- name: Include vars csv2-public-default-vars.yaml
  ansible.builtin.include_vars: "csv2-public-default-vars.yaml"
  when: internal_system_install is not defined

- name: Include vars csv2-public-vars.yaml
  ansible.builtin.include_vars: "csv2-public-vars.yaml"
  when: internal_system_install is not defined

- name: Configure root mail forwarding
  ansible.builtin.import_tasks: configure_root_mail_forwarding.yaml

- name: Create installation directories
  ansible.builtin.import_tasks: create_installation_directories.yaml

- name: Configure other required repositories
  ansible.builtin.import_tasks: configure_other_required_repositories.yaml

- name: Perform yum updates
  ansible.builtin.import_tasks: perform_yum_updates.yaml

- name: Install Configure Firewalld
  ansible.builtin.include_tasks: install_configure_firewalld.yaml

- name: Install other required packages
  ansible.builtin.import_tasks: install_other_required_packages.yaml

- name: Install python3
  ansible.builtin.import_tasks: install_python3.yaml

- name: Create localhost certificate
  ansible.builtin.import_tasks: create_localhost_cert.yaml
  when:
    - local_web is defined
    - local_web

- name: Install configure MariaDB
  ansible.builtin.import_tasks: install_configure_MariaDB.yaml

- name: Create mysql db
  ansible.builtin.import_tasks: create_mysqldb_csv2.yaml

- name: Configure httpd
  ansible.builtin.include_tasks: install_configure_httpd.yaml

- name: Configure letsencrypt certificates
  ansible.builtin.include_tasks: letsencrypt.yaml
  when: (local_web is undefined) or (not local_web)

- name: Install and configure phpmyadmin
  ansible.builtin.import_tasks: install_configure_phpmyadmin.yaml
  when:
    - install_phpMyAdmin is defined
    - install_phpMyAdmin

- name: Install EGI trust anchors
  ansible.builtin.import_tasks: install_EGI_trust_anchors.yaml

- name: Install fetch-crl
  ansible.builtin.import_tasks: install_fetch_crl.yaml

- name: INstall EL7 HTCondor
  ansible.builtin.import_tasks: install_EL7_HTCondor.yaml

- name: Install influxdb
  ansible.builtin.import_tasks: install_influxdb.yaml

- name: Install and configure csv2
  ansible.builtin.import_tasks: install_configure_csv2.yaml

- name: Configure CI target
  ansible.builtin.import_tasks: configure_ci_target.yaml
  when:
    - ci_target is defined
    - ci_target

- name: Create condor poller installation tarball
  ansible.builtin.import_tasks: create_condor_poller_installation_tarball.yaml

- name: Install and start condor poller
  ansible.builtin.import_tasks: install_and_start_condor_poller.yaml

- name: Install and configure filebeat
  ansible.builtin.import_tasks: install_configure_filebeat.yaml
  when:
    - register_ELK is defined
    - register_ELK
    - ELK_server is defined

...
