---
# cloudscheduler (v2) server maim.yaml

- set_fact:
    public_mariadb: false
  when: internal_system_install is not defined

- include_vars: "csv2-public-secrets.yaml"
  when: internal_system_install is not defined
- include_vars: "csv2-public-default-vars.yaml"
  when: internal_system_install is not defined
- include_vars: "csv2-public-vars.yaml"
  when: internal_system_install is not defined

- import_tasks: configure_root_mail_forwarding.yaml

- import_tasks: create_installation_directories.yaml

- import_tasks: configure_backup_directory.yaml

- import_tasks: configure_other_required_repositories.yaml

- import_tasks: perform_yum_updates.yaml

- import_tasks: install_other_required_packages.yaml

- import_tasks: install_python3.yaml

- import_tasks: letsencrypt.yaml
  when: (local_web is undefined) or (local_web == False)

- import_tasks: create_localhost_cert.yaml
  when: 
  - local_web is defined
  - local_web == True

- import_tasks: install_configure_MariaDB.yaml

- import_tasks: create_mysqldb_csv2.yaml

- name: Configure httpd
  include: install_configure_httpd.yaml

- import_tasks: install_configure_phpmyadmin.yaml
  when:
  - install_phpMyAdmin is defined
  - install_phpMyAdmin == True

- import_tasks: install_EGI_trust_anchors.yaml

- import_tasks: install_fetch_crl.yaml

- import_tasks: install_EL7_HTCondor.yaml

- import_tasks: install_influxdb.yaml

- import_tasks: install_configure_csv2.yaml

- import_tasks: configure_ci_target.yaml
  when:
  - ci_target is defined
  - ci_target == True

- import_tasks: create_condor_poller_installation_tarball.yaml

- import_tasks: install_and_start_condor_poller.yaml

- import_tasks: install_configure_filebeat.yaml
  when:
  - register_ELK is defined
  - register_ELK == True
  - ELK_server is defined
