---
# cloudscheduler (v2) server maim.yaml

- name: set_fact
  set_fact:
    public_mariadb: false
  when: internal_system_install is not defined

- name: include_vars
  include_vars: "csv2-public-secrets.yaml"
  when: internal_system_install is not defined
- name: include_vars
  include_vars: "csv2-public-default-vars.yaml"
  when: internal_system_install is not defined
- name: include_vars
  include_vars: "csv2-public-vars.yaml"
  when: internal_system_install is not defined

#- name: set_fact
#  set_fact:
#    favicon_colour: "{{ item.value }}"
#  loop: "{{ lookup('dict', favicon_colours) }}"
#  when:
#  - "{{ item.key  ==  ansible_fqdn }}"

- name: debug
  debug: msg="{{ favicon_colour }}"

- name: set_fact
  set_fact:
    ansible_ssh_port: "{{ ansible_ssh_port }}"
  when: internal_system_install is not defined

- name: import_tasks
  import_tasks: configure_etc_hosts.yaml
- name: import_tasks
  import_tasks: configure_sshd.yaml
  when: ansible_ssh_port != 22
- name: import_tasks
  import_tasks: configure_root_mail_forwarding.yaml
- name: import_tasks
  import_tasks: create_installation_directories.yaml
- name: import_tasks
  import_tasks: configure_other_required_repositories.yaml
- name: import_tasks
  import_tasks: perform_yum_updates.yaml
- name: import_tasks
  import_tasks: install_other_required_packages.yaml
- name: import_tasks
  import_tasks: install_python3.yaml
#- import_tasks: install_python_pip.yaml
- name: import_tasks
  import_tasks: letsencrypt.yaml
  when: (local_web is undefined) or (local_web == False)
- name: import_tasks
  import_tasks: create_localhost_cert.yaml
  when: 
  - local_web is defined
  - local_web == True
#- name: import_tasks
#  import_tasks: configure_network.yaml
#  when:
#  - container is undefined or container != true
#  - reconfigure_network is undefined or reconfigure_network != false
- name: import_tasks
  import_tasks: install_configure_ntpd.yaml
- name: import_tasks
  import_tasks: set_root_user_defaults.yaml
#- name: import_tasks
#  import_tasks: configure_volumes.yaml
#  when: (container is undefined) or (container == False)
#- name: import_tasks
#  import_tasks: configure_users.yaml
#  when: (container is undefined) or (container == False)
#- name: import_tasks
#  import_tasks: configure_sudoers.yaml
#  when: (container is undefined) or (container == False)
#- name: import_tasks
#  import_tasks: configure_swap_file.yaml
- name: import_tasks
  import_tasks: install_configure_MariaDB.yaml
- name: import_tasks
  import_tasks: create_mysqldb_csv2.yaml
- name: include
  include: install_configure_httpd.yaml
- name: import_tasks
  import_tasks: install_configure_phpmyadmin.yaml
  when:
  - install_phpMyAdmin is defined
  - install_phpMyAdmin == True
- name: import_tasks
  import_tasks: install_EGI_trust_anchors.yaml
- name: import_tasks
  import_tasks: install_fetch_crl.yaml
- name: import_tasks
  import_tasks: install_EL7_HTCondor.yaml
- name: import_tasks
  import_tasks: install_configure_csv2.yaml
- name: import_tasks
  import_tasks: configure_ci_target.yaml
  when:
  - ci_target is defined
  - ci_target == True
- name: import_tasks
  import_tasks: create_condor_poller_installation_tarball.yaml
- name: import_tasks
  import_tasks: install_and_start_condor_poller.yaml
- name: import_tasks
  import_tasks: install_configure_filebeat.yaml
  when:
  - register_ELK is defined
  - register_ELK == True
  - ELK_server is defined
- name: import_tasks
  import_tasks: install_influxdb.yaml
