- name: ensure squid directory exists
  file:
    path: /etc/squid
    state: directory

- name: disable SELinux state
  selinux:
    state: disabled

- name: change SELinux to permissive
  shell: sed -i 's/^SELINUX=/SELINUX=permissive \#/g' /etc/sysconfig/selinux

- name: download installer for frontier
  get_url:
    url: http://frontier.cern.ch/dist/rpms/RPMS/noarch/frontier-release-1.2-1.noarch.rpm
    dest: /etc/squid/frontier-release-1.2-1.noarch.rpm

- name: run installer for frontier
  yum:
    name: '/etc/squid/frontier-release-1.2-1.noarch.rpm'
    state: present

- name: install frontier packages
  yum:
    name: ['frontier-squid', 'epel-release']
    state: present

- name: install packages required for python3
  yum:
    name:
    - python3
    - python3-devel
    - python3-pip
    state: installed

- name: install shoal-agent
  command: python3 -m pip install shoal-agent

- name: remove shoal-agent config file
  shell: rm -f /etc/shoal/shoal_agent.conf

- name: create pi
  shell: /usr/sbin/ip -o route get 8.8.8.8 | sed "s/^.* dev \([[:alnum:]]*\) .*/\1/g"
  register: PI

- name: get the ip address
  shell: ip route | grep "{{PI.stdout}}.*link src" | awk '{print $1}'
  register: IP

- name: check for swap file
  stat: 
    path: /swapfile
  register: swap

- name: create swap file
  shell: dd if=/dev/zero of=/swapfile bs=1M count=$((5*1024))
  when: not swap.stat.exists
  
- name: mkswap
  shell: mkswap /swapfile
  when: not swap.stat.exists

- name: swapon
  shell: swapon /swapfile
  when: not swap.stat.exists

- name: get the number of cores
  shell: grep -c 'processor' /proc/cpuinfo
  register: VCORE

- name: create a list of cores
  shell: seq -s, 1 {{VCORE.stdout}}
  register: SEQUENCE

- name: get the total memory
  shell: grep MemTotal /proc/meminfo | awk '{print $2}'
  register: MEM

- name: save 10% of memory for os and convert to MB
  set_fact:
    CACHE_MEM: "{{ ((MEM.stdout | int) / (VCORE.stdout | int) * 9 / 10000) | int }}"

- name: get the disk space 
  shell: df -H --output=avail /var/cache | sed 1d | tr -d "G"
  register: DS

- name: save 20% for disk space and convert to MB
  set_fact:
    CACHE_DIR: "{{ ((DS.stdout | int) / (VCORE.stdout | int) / 5 * 4000) | int }}"

- name: copy customize.sh to the machine
  template:
    src: customize.sh
    dest: /etc/squid/customize.sh
    owner: root
    group: root
    mode: u+x

- name: update owner of customize.sh
  shell: chown squid:squid /etc/squid/customize.sh

- name: enable frontier-squid
  shell: systemctl enable frontier-squid

- name: restart frontier-squid 
  shell: systemctl restart frontier-squid 
  
- name: start frontier-squid
  shell: systemctl start frontier-squid

- name: run shoal agent installer with default options
  shell: (echo -e "\n") | shoal-agent-installation.sh
