- name: ensure squid directory exists
  file:
    path: /etc/squid
    state: directory

- name: copy customize.sh to the machine
  copy:
    src: customize.sh
    dest: /etc/squid/customize.sh
    owner: root
    group: root
    mode: 0755

- name: disable SELinux state
  selinux:
    state: disabled

- name: change SELinux to permissive
  shell: sed -i 's/^SELINUX=/SELINUX=permissive \#/g' /etc/sysconfig/selinux

- name: download installer for frontier
  get_url:
    url: http://frontier.cern.ch/dist/rpms/RPMS/noarch/frontier-release-1.2-1.noarch.rpm
    dest: /etc/squid/frontier-release-1.2-1.noarch.rpm

- name: run installer for frontier
  yum:
    name: '/etc/squid/frontier-release-1.2-1.noarch.rpm'
    state: present

- name: install frontier packages
  yum:
    name: ['frontier-squid', 'epel-release']
    state: present

- name: install packages required for python3
  yum:
    name:
    - python3
    - python3-devel
    - python3-pip
    state: installed

- name: install shoal-agent
  command: python3 -m pip install shoal-agent

- name: remove shoal-agent config file
  shell: rm -f /etc/shoal/shoal_agent.conf

- name: copy init_vars.sh to the machine
  template:
    src: init_vars.sh
    dest: /etc/squid/init_vars.sh
    owner: root
    group: root
    mode: u+x

- name: run init_vars.sh
  shell: /etc/squid/init_vars.sh

- name: update owner of customize.sh
  shell: chown squid:squid /etc/squid/customize.sh

- name: enable frontier-squid
  shell: systemctl enable frontier-squid

- name: restart frontier-squid 
  shell: systemctl restart frontier-squid 
  
- name: start frontier-squid
  shell: systemctl start frontier-squid

- name: run shoal agent installer with default options
  shell: (echo -e "\n") | shoal-agent-installation.sh
