# configure_swap.yaml

- name: check for swap file
  stat:
    path: /swapfile
  register: swap

- name: create swap file
  shell: dd if=/dev/zero of=/swapfile bs=1M count=$((5*1024))
  when: not swap.stat.exists

- name: mkswap
  shell: mkswap /swapfile
  when: not swap.stat.exists

- name: swapon
  shell: swapon /swapfile
  when: not swap.stat.exists
