---
# install_other_required_packages.yaml

- name: enable PowerTools for Centos 8
  command: /usr/bin/dnf config-manager --set-enabled powertools
  when: ansible_facts['distribution_major_version'] == "8"

- name: enable CRB for EL9
  command: dnf config-manager --set-enabled crb
  when: ansible_facts['distribution_major_version'] == "9"

- name: install other required packages for EL7 and EL8
  yum:
    name: ['@development', 'mailx', 'xauth', 'xorg-x11-apps', 'xorg-x11-fonts-Type1']
  when: ansible_facts['distribution_major_version'] in ("7", "8")

- name: install other required packages
  package:
    name: ['@development', 's-nail', 'xauth', 'xorg-x11-fonts-Type1', 'xterm']
    state: latest
  when: ansible_facts['distribution_major_version'] == "9"
