---
# install_configure_ci.yaml

- name: update certificate trust
  command: /usr/bin/update-ca-trust

- name: pull down uvic-heprc-ansible-playbooks
  git:
    repo: https://github.com/hep-gc/uvic-heprc-ansible-playbooks.git
    dest: /opt/deployment/uvic-heprc-ansible-playbooks/
    force: yes
    update: yes
    version: master
    accept_hostkey: yes
  become: no

- name: pull down cloudscheduler repo
  git:
    repo: https://github.com/hep-gc/cloudscheduler.git
    dest: /root/cloudscheduler/
    force: yes
    update: yes
    version: "{{ csv2_branch }}"

- name: ensure csv2 cli config dir exists
  file:
    path: /root/.csv2/unit-test
    state: directory

- name: set cloudscheduler cli default
  copy:
    src: ../files/default_server
    dest: /root/.csv2/default_server
    owner: root
    group: root 

- name: set cloudscheduler cli defauit settings
  copy:
    src: ../files/settings.yaml
    dest: /root/.csv2/unit-test/settings.yaml
    owner: root
    group: root

# ensure pip is intalled
- name: Ensure pip is installed
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

# remove python3-requests yum package (conflicts with openstack pip)
- name: Ensure python3-requests is not present
  ansible.builtin.yum:
    name: python3-requests
    state: absent

# these are also handled in
# /root/cloudscheduler/unit_tests/web_tests/setup_scripts/web_test_setup_full_alma9.sh
- name: Ensure python3 packages are installed
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - requests
    - pytest
    - pytest-rerunfailures
    - selenium
    - requests-toolbelt
    - python-openstackclient
    - python-keystoneclient
    - python-novaclient

- name: Run web test setup script
  ansible.builtin.shell: yes | /root/cloudscheduler/unit_tests/web_tests/setup_scripts/web_test_setup_full_alma9.sh ci_install

- name: Copy credentials file to remote
  ansible.builtin.copy:
    remote_src: false
    src: "{{ csv2_ci_web_credentials_path }}"
    dest: /root/cloudscheduler/unit_tests/credentials.yaml
    mode: "0644"

- name: Copy ssh key to remote
  ansible.builtin.copy:
    remote_src: false
    src: "{{ csv2_ci_ssh_key_path }}"
    dest: /root/.ssh/id_rsa
    mode: "0600"

- name: Enable ssh-agent and add key
  ansible.builtin.shell: |
    eval "$(ssh-agent)"
    ssh-add

# edit ssh config here accoridng to wiki
- name: Configure ssh-config
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    line: "{{ item }}"
  loop:
    - StrictHostKeyChecking no
    - UserKnownHostsFile=/dev/null
...
