---
# install_configure_ci.yaml

- name: update certificate trust
  command: /usr/bin/update-ca-trust

#change the branch back to main before pr
- name: pull down uvic-heprc-ansible-playbooks
  git:
    repo: https://github.com/hep-gc/uvic-heprc-ansible-playbooks.git
    dest: /opt/deployment/uvic-heprc-ansible-playbooks/
    force: yes
    update: yes
    version: csv2-ci-alma9
    # version: master
    accept_hostkey: yes
  become: no

- name: pull down cloudscheduler repo
  git:
    repo: https://github.com/hep-gc/cloudscheduler.git
    dest: /root/cloudscheduler/
    force: yes
    update: yes
    version: "{{ csv2_branch }}"

- name: set up web tests
  shell: yes | /root/cloudscheduler/unit_tests/web_tests/setup_scripts/web_test_setup_full_centos.sh ci_install 

- name: ensure csv2 cli config dir exists
  file:
    path: /root/.csv2/unit-test
    state: directory

- name: set cloudscheduler cli default
  copy:
    src: ../files/default_server
    dest: /root/.csv2/default_server
    owner: root
    group: root 

- name: set cloudscheduler cli defauit settings
  copy:
    src: ../files/settings.yaml
    dest: /root/.csv2/unit-test/settings.yaml
    owner: root
    group: root 
