---
# install_configure_jenkins.yaml

- name: get jenkins long term release repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: import jenkins key from url
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: yum update
  yum:
    name: '*'
    state: latest

- name: install jdk
  yum:
    name: java-11-openjdk-devel
    state: present

- name: install jenkins
  yum:
    name: jenkins
    state: latest

- name: change permissions for ansible directories (1/3)
  file:
    path: /var/lib/jenkins
    owner: root
    group: root
    recurse: yes

- name: change permissions for ansible directories (2/3)
  file:
    path: /var/cache/jenkins
    owner: root
    group: root
    recurse: yes

- name: change permissions for ansible directories (3/3)
  file:
    path: /var/log/jenkins
    owner: root
    group: root
    recurse: yes

- name: make jenkins run as root user (2/3)
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/jenkins.service
    regexp: '^User=.*$'
    line: User=root

- name: make jenkins run as root user (3/3)
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/jenkins.service
    regexp: '^Group=.*$'
    line: Group=root

- name: install jenkins certificate keystore conversion script (depends on letsencrypt)
  template:
    src: usr_local_sbin_prepare_copy_jenkins_keystore.j2
    dest: /usr/local/sbin/prepare_copy_jenkins_keystore
    owner:
    group:
    mode: 0700

- name: create jenkins ssl keystore directory
  ansible.builtin.file: 
    state: directory
    path: /etc/systemd/system/jenkins.service.d
    owner: root
    group: root
    mode: 0700

- name: run copy jenkins keystore
  ansible.builtin.shell: yes | /usr/local/sbin/prepare_copy_jenkins_keystore
    

- name: install custom jenkins config for SSL
  template:
    src: etc_systemd_system_jenkins.service.d_override.conf.j2
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    owner: root
    group: root
    mode: 0700

- name: install jenkins keystore conversion cron task
  copy:
    src: etc_cron.d_prepare_copy_jenkins_keystore
    dest: /etc/cron.d/prepare_copy_jenkins_keystore
    owner: root
    group: root
    mode: 0644

- name: daemon-reload to pick up config changes
  systemd:
    daemon_reload: yes

- name: open jenkins ssl port (if firewalld is installed)
  command: firewall-cmd --permanent --zone=public --add-port=8443/tcp
  notify:
    - restart firewalld
  ignore_errors: yes  


- name: start jenkins
  systemd:
    name: jenkins
    enabled: yes
    state: restarted
    
