---
# ci server main.yaml

- name: Include vars
  ansible.builtin.include_vars: csv2-ci-vars.yaml

- name: Include install_firewalld
  ansible.builtin.include_tasks: install_firewalld.yaml

- name: Include create_installation_directories
  ansible.builtin.include_tasks: create_installation_directories.yaml

- name: Configure backup directory
  include: configure_backup_directory.yaml

- name: Include perform_yum_updates
  ansible.builtin.include_tasks: perform_yum_updates.yaml

- name: Include install_other_required_packages
  ansible.builtin.include_tasks: install_other_required_packages.yaml

- name: Include install_configure_ci
  ansible.builtin.include_tasks: install_configure_ci.yaml

- name: Include install_configure_jenkins
  ansible.builtin.include_tasks: install_configure_jenkins.yaml

...
