# install_configure_rabbitmq.yaml

- name: determine the distribution version
  set_fact:
    distribution: "{{ '7' if ansible_facts['distribution_major_version'] == '7' else '8' }}"

- name: get the erlang script
  get_url:
    url: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    dest: /tmp/erlang_script.rpm.sh
    mode: a+x

- name: execute the script
  shell: sudo os=el dist="{{ distribution }}" /tmp/erlang_script.rpm.sh

- name: install erlang
  yum: 
    name: erlang

- name: get the script for rabbitmq
  get_url:
    url: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh
    dest: /tmp/rabbitmq_script.rpm.sh
    mode: a+x

- name: execute the script
  shell: sudo os=el dist="{{ distribution }}" /tmp/rabbitmq_script.rpm.sh

- name: Install RabbitMQ server
  yum:
    name: rabbitmq-server
    state: installed
    update_cache: true
  register: rabbitmqinstalled

- name: create the RabbitMQ config file
  copy:
    src: etc_rabbitmq_rabbitmq.conf
    dest: /etc/rabbitmq/rabbitmq.conf