---
# file: install_python3.yaml.

- name: ensure python36u is not installed
  yum:
    name:
      - python36u
      - python36u-devel
      - python36u-libs
      - python36u-pip
      - python36u-setuptools
    state: absent
  ignore_errors: yes

- name: ensure python36u repositories are not installed
  file:
      path: "/etc/yum.repos.d/{{ item }}.repo"
      state: absent
  with_items:
  - ius
  - ius-archive
  - iut-testing
  ignore_errors: yes

- name: install packages required for python3
  yum:
    name:
      - python3
      - python3-devel
      - python3-pip
    state: installed

