#file: add_s3_credentials.yaml

- name: Add bucket access key
  template:
    src: access_key
    dest: /etc/xrootd/access_key
    owner: xrootd
    group: xrootd

- name: Add bucket secret key
  template:
    src: secret_key
    dest: /etc/xrootd/secret_key
    owner: xrootd
    group: xrootd

- name: Add s3 config file
  template:
    src: s3cfg
    dest: /etc/xrootd/s3cfg
    owner: xrootd
    group: xrootd
