# file: configure_grid_security.yaml
# Assumes: /etc/grid-security/hostcert.pem and /etc/grid-security/hostkey.pem exist on the host node.
---

- name: Create grid-mapfile
  copy:
    src: grid-mapfile
    dest: /etc/grid-security/grid-mapfile

- name: Ensure xrd directory exists
  file:
    path: /etc/grid-security/xrd
    state: directory

- name: Add xrdcert
  copy:
    remote_src: true
    src: /etc/grid-security/hostcert.pem
    dest: /etc/grid-security/xrd/xrdcert.pem
    owner: xrootd
    group: xrootd
    mode: 0644
    
- name: Add xrdkey
  copy:
    remote_src: true
    src: /etc/grid-security/hostkey.pem
    dest: /etc/grid-security/xrd/xrdkey.pem
    owner: xrootd
    group: xrootd
    mode: 0600

- name: Ensure belle vomsdir directory exists
  file:
    path: /etc/grid-security/vomsdir/belle
    state: directory

- name: Ensure vomses directory exists
  file:
    path: /etc/vomses
    state: directory

- name: Add KEK voms file
  copy:
    src: voms.cc.kek.jp.pem
    dest: /etc/grid-security/vomsdir/belle/voms.cc.kek.jp.pem


- name: add vomses file
  copy: 
    src: etc_vomses_belle
    dest: /etc/vomses/belle
