# file: configure_grid_security.yaml
#
# Depends on the following variables:
# "{{hostcert}}"
# "{{hostkey}}"

- name: Create grid-mapfile
  copy:
    src: grid-mapfile
    dest: /etc/grid-security/grid-mapfile

- name: Ensure xrd directory exists
  file:
    path: /etc/grid-security/xrd
    state: directory

- name: Copy hostcert
  copy: 
    src: "{{hostcert}}"
    dest: /etc/grid-security/hostcert.pem
    owner: root
    group: root

- name: Copy hostkey
  copy:
    src: "{{hostkey}}"
    dest: /etc/grid-security/hostkey.pem
    owner: root
    group: root
    mode: 0600

- name: Add xrdcert
  copy:
    src: "{{hostcert}}"
    dest: /etc/grid-security/xrd/xrdcert.pem
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
- name: Add xrdkey
  copy:
    src: "{{hostkey}}"
    dest: /etc/grid-security/xrd/xrdkey.pem
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0600

- name: Ensure belle directory exists
  file:
    path: /etc/grid-security/vomsdir/belle
    state: directory

- name: Add KEK voms file
  copy:
    src: voms.cc.kek.jp.lsc
    dest: /etc/grid-security/vomsdir/belle/voms.cc.kek.jp.lsc
