# file: configure_xrootd.yaml
#
# Depends on the following variables:
# {{data_dir}}
# {{localroot}}

- name: Add xrootd configuration
  template:
    src: xrootd-tpc.cfg
    dest: "/etc/xrootd/xrootd-tpc.cfg"
    owner: xrootd
    group: xrootd
- name: Add Authfile
  template:
    src: Authfile
    dest: "/etc/xrootd/Authfile"
    owner: xrootd
    group: xrootd
- name: Ensure localroot exists
  file:
    path: "{{localroot}}"
    state: directory
- name: Change ownership of localroot and sub-directories if it exists
  file:
    path: "{{localroot}}"
    state: directory
    owner: xrootd
    group: xrootd
    recurse: true
- name: Add the tpc script
  copy:
    src: tpc.sh
    dest: "/etc/xrootd/xrootd-tpc.sh"
    owner: xrootd
    group: xrootd
    mode: u+x
- name: Generate macaroon secret
  command: 
    cmd: openssl rand -base64 -out /etc/xrootd/macaroon-secret 64
    creates: "/etc/xrootd/macaroon-secret"
- name: Enable XRootD service
  systemd:
    name: xrootd@tpc
    enabled: true
    state: started
