- name: Create grid-mapfile
  copy:
    src: grid-mapfile
    dest: /etc/grid-security/grid-mapfile

- name: Ensure xrd directory exists
  file:
    path: /etc/grid-security/xrd
    state: directory

# TODO copy the keys and certificates
- name: Copy hostcert
  copy: 
    src: "{{suffix}}_cert.pem"
    dest: /etc/grid-security/hostcert.pem
    owner: root
    group: root

- name: Copy hostkey
  copy:
    src: "{{suffix}}_key.pem"
    dest: /etc/grid-security/hostkey.pem
    owner: root
    group: root
    mode: 0600

- name: Add xrdcert
  copy:
    src: "{{suffix}}_cert.pem"
    dest: /etc/grid-security/xrd/xrdcert.pem
    owner: centos
    group: centos
- name: Add xrdkey
  copy:
    src: "{{suffix}}_key.pem"
    dest: /etc/grid-security/xrd/xrdkey.pem
    owner: centos
    group: centos
    mode: 0600

- name: Ensure belle directory exists
  file:
    path: /etc/grid-security/vomsdir/belle
    state: directory

- name: Add KEK voms file
  copy:
    src: voms.cc.kek.jp.lsc
    dest: /etc/grid-security/vomsdir/belle/voms.cc.kek.jp.lsc
