# file: configure_xrootd.yaml
#
# Depends on the following variables:
# {{export_path}}
# {{localroot}}

- name: Add xrootd server configuration
  template:
    src: xrootd-configuration
    dest: "/etc/xrootd/xrootd-{{server_type}}.cfg"
    owner: xrootd
    group: xrootd

- name: Add Authfile
  template:
    src: Authfile
    dest: "/etc/xrootd/Authfile"
    owner: xrootd
    group: xrootd

- name: Ensure localroot exists
  file:
    path: "{{localroot}}"
    state: directory

- name: Change ownership of localroot and sub-directories if it exists
  file:
    path: "{{localroot}}"
    state: directory
    owner: xrootd
    group: xrootd
    recurse: true

- name: Add the standalone tpc script
  copy:
    src: tpc.sh
    dest: "/etc/xrootd/tpc.sh"
    owner: xrootd
    group: xrootd
    mode: u+x
  when: server_type == "standalone"

- name: Add the s3 tpc script
  copy:
    src: tpc-s3.sh
    dest: "/etc/xrootd/tpc.sh"
    owner: xrootd
    group: xrootd
    mode: u+x
  when: server_type == "s3_proxy"

- name: Create directory matching bucket name as a workaround for pss
  file:
    path: "{{bucket_name}}"
    state: directory
  when: server_type == "s3_proxy"

- name: Generate macaroon secret
  command: 
    cmd: openssl rand -base64 -out /etc/xrootd/macaroon-secret 64
    creates: "/etc/xrootd/macaroon-secret"

- name: Enable XRootD service
  systemd:
    name: xrootd@{{server_type}}
    enabled: true
    state: restarted
