---
# file: install_OSG_repository.yaml
- name: Install yum-plugin-priorities
  yum:
    name: yum-plugin-priorities
    state: latest

- name: Install OSG 3.6 for EL7
  yum:
    name: https://repo.opensciencegrid.org/osg/3.6/osg-3.6-el7-release-latest.rpm
    state: present
