- name: Install XrootD packages
  yum:
    name: xrootd, voms, xrootd-voms
    state: latest
- name: Add xrootd configuration
  copy:
    src: tpc-macaroons.conf
    dest: /home/centos/tpc-macaroons.conf
- name: Add Authfile
  copy:
    src: Authfile
    dest: /home/centos/Authfile
- name: Make data directory
  file:
    path: /home/centos/data
    state: directory
    owner: centos
    group: centos
- name: Add the tpc script
  copy:
    src: tpc.sh
    dest: /home/centos/tpc.sh
    owner: centos
    group: centos
    mode: u+x
- name: Generate macaroon secret
  command: 
    cmd: openssl rand -base64 -out /home/centos/macaroon-secret 64
    creates: /home/centos/macaroon-secret