#file: install_xrootd.yaml

- name: Install XrootD packages
  package:
    name: xrootd, xrootd-voms, xrootd-client
    state: latest

- name: open xrootd port 1094
  firewalld: zone=public port=1094/tcp state=enabled permanent=true
  notify:
    - restart firewalld
