# # s3_storage_stats.yaml
# ---

- name: install python3
  yum:
    name: python3

- name: create s3 proxy log directory
  file:
    state: directory
    path: /var/log/xrootd/s3_proxy
    owner: root
    group: root

- name: create log file for storage-stats
  file:
    state: touch
    path: /var/log/xrootd/s3_proxy/storage_stats.log
    owner: root
    group: root

- name: install s3-storage-stats
  command: python3 -m pip install s3-storage-stats>=1.0.4
