# file: install_and_configure_xrootd.yaml

- name: Install XrootD packages
  package:
    name: xrootd, voms, xrootd-voms
    state: latest
- name: Add xrootd configuration
  template:
    src: tpc-macaroons.conf
    dest: "{{xrddir}}/tpc-macaroons.conf"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
- name: Add Authfile
  template:
    src: Authfile
    dest: "{{xrddir}}/Authfile"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
- name: Make data directory
  file:
    path: "{{data_dir}}"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
- name: Add the tpc script
  copy:
    src: tpc.sh
    dest: "{{xrddir}}/tpc.sh"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: u+x
- name: Generate macaroon secret
  command: 
    cmd: openssl rand -base64 -out {{xrddir}}/macaroon-secret 64
    creates: "{{xrddir}}/macaroon-secret"
    