# file: install_and_configure_xrootd.yaml
#
# Depends on the following variables:
# {{data_dir}}
# {{localroot}}

- name: Install XrootD packages
  package:
    name: xrootd, xrootd-voms
    state: latest
- name: Add xrootd configuration
  template:
    src: xrootd-tpc.cfg
    dest: "/etc/xrootd/xrootd-tpc.cfg"
    owner: xrootd
    group: xrootd
- name: Add Authfile
  template:
    src: Authfile
    dest: "/etc/xrootd/Authfile"
    owner: xrootd
    group: xrootd
- name: Check if data directory exists
  stat:
    path: "{{localroot}}{{data_dir}}"
  register: data_dir_stat
- name: Change ownership of data directory if it exists
  when: data_dir_stat.stat.exists and data_dir_stat.stat.isdir
  file:
    path: "{{localroot}}{{data_dir}}"
    state: directory
    owner: xrootd
    group: xrootd
- name: Add the tpc script
  copy:
    src: tpc.sh
    dest: "/etc/xrootd/tpc.sh"
    owner: xrootd
    group: xrootd
    mode: u+x
- name: Generate macaroon secret
  command: 
    cmd: openssl rand -base64 -out /etc/xrootd/macaroon-secret 64
    creates: "/etc/xrootd/macaroon-secret"
- name: Enable XRootD service
  systemd:
    name: xrootd@tpc
    enabled: true
    state: started
