# file: install_and_configure_xrootd.yaml
#
# Depends on the following variables:
# {{xrddir}}
# {{data_dir}}
# {{localroot}}

- name: Install XrootD packages
  package:
    name: xrootd, voms, xrootd-voms
    state: latest
- name: Add xrootd configuration
  template:
    src: xrootd-tpc.cfg
    dest: "{{xrddir}}/xrootd-tpc.cfg"
    owner: xrootd
    group: xrootd
- name: Add Authfile
  template:
    src: Authfile
    dest: "{{xrddir}}/Authfile"
    owner: xrootd
    group: xrootd
- name: Make data directory
  file:
    path: "{{localroot}}{{data_dir}}"
    state: directory
    owner: xrootd
    group: xrootd
- name: Add the tpc script
  copy:
    src: tpc.sh
    dest: "{{xrddir}}/tpc.sh"
    owner: xrootd
    group: xrootd
    mode: u+x
- name: Generate macaroon secret
  command: 
    cmd: openssl rand -base64 -out {{xrddir}}/macaroon-secret 64
    creates: "{{xrddir}}/macaroon-secret"
- name: Enable XRootD service
  systemd:
    name: xrootd@tpc
    enabled: true
    state: started
