# Xrootd server setup yaml
---
- include_vars: xrootd_vars.yaml

- import_tasks: install_EGI_trust_anchors.yaml
- import_tasks: install_epel_repository.yaml
- import_tasks: install_fetch_crl.yaml
# It seems to be necessary to install xrootd from the OSG repo to have fully working TPC
#- import_tasks: install_OSG_repository.yaml
- import_tasks: install_xrootd.yaml
- import_tasks: configure_grid_security.yaml
- import_tasks: configure_xrootd.yaml